import { v4 as uuid } from "uuid";
export const courses = [
  {
    id: uuid(),
    title: "HTML,CSS and JS",
    price: 150,
    current: 100,
    img: "./src/images/htmlcss.jpg",
    instructor: "John",
  },
  {
    id: uuid(),
    title: "Trading masterclass",
    price: 200,
    current: 150,
    img: "./src/images/trading.jpg",
    instructor: "Peter",
  },
  {
    id: uuid(),
    title: "Artificial intelligence",
    price: 300,
    current: 200,
    img: "./src/images/ai.jpg",
    instructor: "Moris",
  },
  {
    id: uuid(),
    title: "Blogging for beginners",
    price: 150,
    current: 100,
    img: "./src/images/blogging.jpg",
    instructor: "Lisa",
  },
  {
    id: uuid(),
    title: "Cyber security masterclass",
    price: 450,
    current: 350,
    img: "./src/images/cyber-security.jpg",
    instructor: "John",
  },
  {
    id: uuid(),
    title: "Blockchain",
    price: 350,
    current: 250,
    img: "./src/images/blockchain.jpg",
    instructor: "Steven",
  },
  {
    id: uuid(),
    title: "Digital marketing",
    price: 150,
    current: 80,
    img: "./src/images/dm.jpg",
    instructor: "Shauna",
  },
  {
    id: uuid(),
    title: "Drawing",
    price: 100,
    current: 50,
    img: "./src/images/drawing.jpg",
    instructor: "Charlie",
  },
  {
    id: uuid(),
    title: "Flutter development",
    price: 200,
    current: 120,
    img: "./src/images/flutter.jpg",
    instructor: "Fiona Watson",
  },
  {
    id: uuid(),
    title: "Leadership skills",
    price: 150,
    current: 100,
    img: "./src/images/leadership.jpg",
    instructor: "Liam Miller",
  },
  {
    id: uuid(),
    title: "NodeJS",
    price: 180,
    current: 150,
    img: "./src/images/nodejs.jpg",
    instructor: "John Smilga",
  },
  {
    id: uuid(),
    title: "Online courses creation",
    price: 100,
    current: 70,
    img: "./src/images/online.jpg",
    instructor: "Chris",
  },
  {
    id: uuid(),
    title: "Programming basics",
    price: 100,
    current: 60,
    img: "./src/images/programming.jpg",
    instructor: "Hitesh",
  },
  {
    id: uuid(),
    title: "ReactJS development",
    price: 200,
    current: 150,
    img: "./src/images/reactjs.jpg",
    instructor: "John Smilga",
  },
  {
    id: uuid(),
    title: "S.E.O",
    price: 150,
    current: 100,
    img: "./src/images/seo.jpg",
    instructor: "Louise",
  },
];
