import { v4 as uuid } from "uuid";
export const courses = [
  {
    id: uuid(),
    title: "HTML,CSS and JS",
    price: 150,
    current: 100,
    img: "/images/htmlcss.jpg",
    instructor: "John",
  },
  {
    id: uuid(),
    title: "Angular course",
    price: 200,
    current: 120,
    img: "/images/angular.jpg",
    instructor: "Robert",
  },
  {
    id: uuid(),
    title: "Python for AI/ML",
    price: 250,
    current: 200,
    img: "/images/python.jpg",
    instructor: "Hitesh",
  },
  {
    id: uuid(),
    title: "Php course",
    price: 150,
    current: 80,
    img: "/images/php.jpg",
    instructor: "Harry",
  },
  {
    id: uuid(),
    title: "VueJS course",
    price: 180,
    current: 130,
    img: "/images/vue.jpeg",
    instructor: "Tina",
  },
  {
    id: uuid(),
    title: "Trading masterclass",
    price: 200,
    current: 150,
    img: "/images/trading.jpg",
    instructor: "Peter",
  },
  {
    id: uuid(),
    title: "Artificial intelligence",
    price: 300,
    current: 200,
    img: "/images/ai.jpg",
    instructor: "Moris",
  },
  {
    id: uuid(),
    title: "Blogging for beginners",
    price: 150,
    current: 100,
    img: "/images/blogging.jpg",
    instructor: "Lisa",
  },
  {
    id: uuid(),
    title: "Cyber security masterclass",
    price: 450,
    current: 350,
    img: "/images/cyber-security.jpg",
    instructor: "John",
  },
  {
    id: uuid(),
    title: "Blockchain",
    price: 350,
    current: 250,
    img: "/images/blockchain.jpg",
    instructor: "Steven",
  },
  {
    id: uuid(),
    title: "Digital marketing",
    price: 150,
    current: 80,
    img: "/images/dm.jpg",
    instructor: "Shauna",
  },
  {
    id: uuid(),
    title: "Drawing",
    price: 100,
    current: 50,
    img: "/images/drawing.jpg",
    instructor: "Charlie",
  },
  {
    id: uuid(),
    title: "Flutter development",
    price: 200,
    current: 120,
    img: "/images/flutter.jpg",
    instructor: "Fiona Watson",
  },
  {
    id: uuid(),
    title: "Leadership skills",
    price: 150,
    current: 100,
    img: "/images/leadership.jpg",
    instructor: "Liam Miller",
  },
  {
    id: uuid(),
    title: "NodeJS",
    price: 180,
    current: 150,
    img: "/images/nodejs.jpg",
    instructor: "John Smilga",
  },
  {
    id: uuid(),
    title: "Online courses creation",
    price: 100,
    current: 70,
    img: "/images/online.jpg",
    instructor: "Chris",
  },
  {
    id: uuid(),
    title: "Programming basics",
    price: 100,
    current: 60,
    img: "/images/programming.jpg",
    instructor: "Hitesh",
  },
  {
    id: uuid(),
    title: "ReactJS development",
    price: 200,
    current: 150,
    img: "/images/reactjs.jpg",
    instructor: "John Smilga",
  },
  {
    id: uuid(),
    title: "S.E.O",
    price: 150,
    current: 100,
    img: "/images/seo.jpg",
    instructor: "Louise",
  },
];
